### ISSUE TITLE
Give me back zoom controls.

### ISSUE THREAD

**Issue by jwietelmann** [bhuga/hackable-slack-client#1]
Official Slack client has Command+ and Command- to zoom in and out. Is there a way for you to expose those shortcuts from Chrome (which has the same)?

**Comment by bhuga** [comment]
Seems perfectly doable: https://github.com/atom/electron/blob/master/docs/api/web-frame.md#methods

Will do it the next time I poke at this, probably tonight (and hopefully get the code signing issue solved, so auto-update works).
