### ISSUE TITLE
Support Slack's Command+[ and Command+] shortcuts

### ISSUE THREAD

**Issue by jasonrudolph** [bhuga/hackable-slack-client#13]
In the vanilla Slack client, you can use `Command+[` and  `Command+]` to navigate back and forward in history respectively:

![slack](https://cloud.githubusercontent.com/assets/2988/16395121/66f7a4ac-3c86-11e6-806d-1202522e1ac5.png)

In hackable-slack-client, these shortcuts seem to be ignored. It would be awesome if hackable-slack-client supported these shortcuts.

**Comment by mistydemeo** [comment]
Looks like they're mapped to `cmd-left` and `cmd-right`, maybe because it's actually bound to the history-back and history-forward events?

**Comment by bhuga** [comment]
> maybe because it's actually bound to the history-back and history-forward events?

That is indeed the case. They just call `window.history.go(-1)`. I've implemented this, working the same way their client does, as a bonus in #12.
