### ISSUE TITLE
Slack Beta - Electron

### ISSUE THREAD

**Issue by astanciu** [bhuga/hackable-slack-client#15]
Was just curious, now that Slack is built with Electron, do you have any plans for changing the hackable client to be injectable into the normal slack app?

**Comment by bhuga** [comment]
Unless the normal app becomes open source (unlikely), this won't happen. Electron wasn't a key technology other than being the easiest way to write a wrapper that it allows us to run javascript after the page has loaded. Without those hooks, the normal app being electron doesn't put us in a better place than MacGap did.
