### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by ErinCall** [bhuga/hackable-slack-client#16]
After waking my computer from sleep, everything seemed to be fine except that clicking on links popped up an error dialog:

```
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: expose-window-apis.js:8:43.
    at EventEmitter.ret (/Applications/Hackable Slack Client.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:168:19)
    at emitMany (events.js:113:20)
    at EventEmitter.emit (events.js:182:7)
```

Restarting fixed it, and it looks like it's probably an Electron thing anyway, but I thought I'd write it down in case it looks familiar

**Comment by bhuga** [comment]
It's https://github.com/electron/electron/issues/3778. I'm not sure if it's a bug or what yet.
