### ISSUE TITLE
SSB app has been deprecated

### ISSUE THREAD

**Issue by mistydemeo** [bhuga/hackable-slack-client#22]
hackable-slack-client connects to the `/ssb` URL. Slack has deprecated their older SSB app in favour of their new Electron app, and has started showing deprecation modals on every signon:

<img width="650" alt="screen shot 2017-03-28 at 1 40 48 pm" src="https://cloud.githubusercontent.com/assets/780485/24387586/aacc9bc0-13c1-11e7-8927-0dde0205e18a.png">

**Comment by mistydemeo** [comment]
The modal display logic comes from `rollup-client.js`, in the `onStart`, in one of these two conditions:

```js
if (TS.qs_args.deprecate_modal_ssb) {
    _showSSBDeprecationModal()
}

// or

if (TS.client.deprecation.isDeprecatedSSB()) {
    _showSSBDeprecationModal()
}
```

**Comment by bhuga** [comment]
Yuck. And I'm not going to get to it tonight, my traditional night 😞

**Comment by bhuga** [comment]
Bumping electron seems to have fixed this. I'm going to ignore it for now; I'm not confident that anything I do in the meantime won't be obsolete by the time we need it again.
