### ISSUE TITLE
shift+up in long messages scrolls history rather than selecting text

### ISSUE THREAD

**Issue by ErinCall** [bhuga/hackable-slack-client#8]
Steps:
1. type a lot of words in the message field; enough that it goes to at least two lines high
2. put the cursor on the second or lower line
3. press shift+up

Expected result: text will be selected

Actual result: previous message appears in the message field

**Comment by bhuga** [comment]
Keep the bug reports coming :bow:

Might have a chance to get to this in my meetup tonight

**Comment by ErinCall** [comment]
:bow:
